---
openapi: 3.1.0
components:
  schemas:
    AddIngredientRequest:
      type: object
      properties:
        ingredientName:
          type: string
    ConfirmImportRequest:
      type: object
      properties:
        recipes:
          type: array
          items:
            $ref: "#/components/schemas/ConfirmedRecipe"
    ConfirmedRecipe:
      type: object
      properties:
        recipeName:
          type: string
        pageNumber:
          type: integer
          format: int32
        ingredient:
          type: string
        keep:
          type: boolean
    CreateCookbookRequest:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
    MergeIngredientsRequest:
      type: object
      properties:
        targetId:
          $ref: "#/components/schemas/UUID"
        sourceIds:
          type: array
          items:
            type: string
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
    UUID:
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
    UpdateIngredientRequest:
      type: object
      properties:
        name:
          type: string
        disambiguations:
          type: array
          items:
            type: string
        availableMonths:
          type: array
          items:
            type: integer
            format: int32
paths:
  /api/cookbooks:
    get:
      parameters:
      - name: q
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: List Cookbooks
      tags:
      - Cookbook Resource
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCookbookRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Create Cookbook
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Cookbook
      tags:
      - Cookbook Resource
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Delete Cookbook
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}/confirm:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfirmImportRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Confirm Import
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}/cover:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Upload Cover
      tags:
      - Cookbook Resource
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            image/jpeg: {}
            image/png: {}
      summary: Get Cover
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}/index-pages:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Upload Index Pages
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}/ocr/results:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Ocr Results
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}/ocr/start:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Start Ocr Processing
      tags:
      - Cookbook Resource
  /api/cookbooks/{id}/recipes:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Cookbook Recipes
      tags:
      - Cookbook Resource
  /api/ingredients:
    get:
      parameters:
      - name: availableNow
        in: query
        schema:
          type: boolean
      - name: cursor
        in: query
        schema:
          $ref: "#/components/schemas/UUID"
      - name: hasDisambiguations
        in: query
        schema:
          type: boolean
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: minRecipeCount
        in: query
        schema:
          type: integer
          format: int32
      - name: q
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: List Ingredients
      tags:
      - Ingredient Resource
  /api/ingredients/merge:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MergeIngredientsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Merge Ingredients
      tags:
      - Ingredient Resource
  /api/ingredients/{id}:
    put:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateIngredientRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Update Ingredient
      tags:
      - Ingredient Resource
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Ingredient
      tags:
      - Ingredient Resource
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Delete Ingredient
      tags:
      - Ingredient Resource
  /api/ingredients/{id}/recipes:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      - name: cookbookId
        in: query
        schema:
          $ref: "#/components/schemas/UUID"
      - name: cursor
        in: query
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: q
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Ingredient Recipes
      tags:
      - Ingredient Resource
  /api/recipes:
    get:
      parameters:
      - name: availableNow
        in: query
        schema:
          type: boolean
      - name: cookbookId
        in: query
        schema:
          $ref: "#/components/schemas/UUID"
      - name: cursor
        in: query
        schema:
          type: string
      - name: ingredient
        in: query
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: q
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: List Recipes
      tags:
      - Recipe Resource
  /api/recipes/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Recipe
      tags:
      - Recipe Resource
  /api/recipes/{id}/ingredients:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddIngredientRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Add Ingredient
      tags:
      - Recipe Resource
info:
  title: the-recipe-db API
  version: 1.0-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
